# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1namJ60rii-ePj7Qg9_7L-3-sghCZGqO_
"""

import numpy as np
import pandas as pd

df=pd.read_csv('Experiment5.csv')

df.head(10)

total_records=10
no_golf=4
print("The unconditional probability of golf is",no_golf/total_records)
no_medrisk=3
probability_medRisk=3/10
print("The probability of medRisk",probability_medRisk)
no_single_medRisk=2
probability_single_and_medRisk=no_single_medRisk/total_records
print("The probability of single and medrisk",probability_single_and_medRisk)
print("The probability of single given medrisk",probability_single_and_medRisk/probability_medRisk)